<a href="https://colab.research.google.com/github/Aditi15091999/AML-Assignments/blob/main/AMl_Lab_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

find the shape and type of (a,a*2)

In [ ]:
import numpy as np
a=np.arange(10).reshape(2,5)
z=np.vstack((a,a*2))
print(z)
print(z.shape)
print(z.dtype)

b=np.arange(10)*2
np.array(b)
print(b)
print(b.shape)
print(b.dtype)



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 0  2  4  6  8]
 [10 12 14 16 18]]
(4, 5)
int64
[ 0  2  4  6  8 10 12 14 16 18]
(10,)
int64


In [ ]:
 arr=np.array([4, -3, -2, 1, 3, 4])
 print(arr)


[ 4 -3 -2  1  3  4]


find sum of the elements in the array  

In [ ]:
#sum of the elements in the array  
print(sum(arr))

7


 find the small and big elements of the array

In [ ]:
print(min(arr)) #prints the smallest element in the array

-3


In [ ]:
print(max(arr))#prints the largest element in the array

4


find the mean and standard deviation of the array elements

In [ ]:
print(arr.mean())#mean of the array elements

1.1666666666666667


In [ ]:
print(arr.std())#standard deviation of elements

2.793842435706702


find the index of the biggest and smallest elements of the array

In [ ]:
print(arr.argmax())#index of maximum element

0


In [ ]:
print(arr.argmin())#index of minimum element

1


find the dot product of (2j, 3j), (3j, 2j)

In [ ]:
arr1=np.array([2j,3j])
arr2=np.array([3j,2j])
np.dot(arr1,arr2) #performs the dot product

(-12+0j)

create an array which contain square of all integer numbers between 0 and 13

In [ ]:
arr3=np.arange(13)**2 #returns the square of the elements uptil 12
arr3


array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

Use bracket notation to get value particular index

In [ ]:
arr5=np.random.randint(-5,9,size=10)
print(arr5)

[-4  8  8  3  1 -3 -1 -4  6 -3]


In [ ]:
arr5[4] #returns the 4th element in the array

1

In [ ]:
arr5[:5] #returns elements of the array till the 4th index excluding 5th element


array([-4,  8,  8,  3,  1])

In [ ]:
arr5[2:6] #returns the elements corresponding to index 2 to index 5

array([ 8,  3,  1, -3])

In [ ]:
arr5[-4]#returns the 4th element from the back of the array

-1

In [ ]:
arr5[-4:-1] # returns the  4th elemnt from the back of the array till the last but one element

array([-1, -4,  6])

In [ ]:
arr5[-4: ] #returns all the elements from the index -4 to the end of the array

array([-1, -4,  6, -3])

In [ ]:
arr5[-5::-2] #returns the elements from the 5th index from behind of the array with steps of -2


array([-3,  3,  8])

In [ ]:
arr5[-5::2] #returns the elements from the 5th index from behind of the array with steps of 2

array([-3, -4, -3])